### ISSUE TITLE
 App can not be installed

### ISSUE THREAD

**Issue by neupanedipen** [Cobrijani/CyFile#31]
#### Expected behavior<br>
I should be able to install the app after downloading the apk file.<br>
#### Actual behavior<br>
But the app shows parsing error after downloading the apk and trying to install it.<br>
#### How to reproduce<br>
1. Download the apk file from releases page.<br>
2. Try to package install the app.<br>
The app can&apos;t be installed and shows parsing error.<br>
* App Version: 1.0<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/I7XeJSiPLmM

**Comment by Cobrijani** [comment]
Hey,
Thank you for reporting.

Gonna fix the apk soon!

**Comment by neupanedipen** [comment]
That would be great. Thank you!

**Comment by Cobrijani** [comment]
The api is resigned and rebuilt, can you check it out?

**Comment by Cobrijani** [comment]
Fixed
